[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "uvicorn api:app --host 0.0.0.0 --port $PORT"
healthcheckEnabled = false
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
