[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 5

# No need for healthcheck or custom start command
# The Dockerfile CMD will be used automatically
